services:

  camunda-bpm-platform-7:
    image: camunda/camunda-bpm-platform:run-7.22.0
    ports:
      - '9090:8080'
    environment:
     CAMUNDA_BPM_DEFAULT-SERIALIZATION-FORMAT: "application/json"

    command:
      - './camunda.sh'
      - '--rest'
      - '--webapps'

  worker-database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: worker-database
