spring:
  jpa:
    open-in-view: true

dev:
  bpm-crafters:
    process-api:
      adapter:
        c8:
          user-tasks:
            delivery-strategy: subscription_refreshing
            completion-strategy: job
            fixed-rate-schedule-rate: 5000 # every 5 seconds
            tasklist-url: UNUSED
            fixed-rate-refresh-rate: 5000 # every 5 seconds
          service-tasks:
            delivery-strategy: subscription
            worker-id: worker

zeebe:
  client:
    cloud:
      region: ${ZEEBE_REGION}
      clusterId: ${ZEEBE_CLUSTER_ID}
      clientId: ${ZEEBE_CLIENT_ID}
      clientSecret: ${ZEEBE_CLIENT_SECRET}

springdoc:
  swagger-ui:
    try-it-out-enabled: true
