spring:
  application:
    name: Order Fulfillment Local Self-Managed

zeebe:
  client:
    broker:
      gateway-address: localhost:26500
    connection-mode: ADDRESS
    security:
      plaintext: true

logging:
  level:
    io.camunda.common.auth.DefaultNoopAuthentication: OFF
