spring:
  jpa:
    open-in-view: true
dev:
  bpm-crafters:
    process-api:
      adapter:
        c7:
          embedded:
            external-service-tasks:
              delivery-strategy: embedded_job
              worker-id: embedded-worker
              lock-time-in-seconds: 10
              execute-initial-pull-on-startup: true
            user-tasks:
              delivery-strategy: embedded_job
              execute-initial-pull-on-startup: true
