spring:
  jpa:
    open-in-view: true

server:
  port: 8080

springdoc:
  swagger-ui:
    try-it-out-enabled: true

logging:
  level:
    org.springframework.context.support.[PostProcessorRegistrationDelegate$BeanPostProcessorChecker]: ERROR
